### PR TITLE
Update tailwindcss settings

### LINKED ISSUE #395: Poor performance of ESlint with tailwind rules
When profiling the forerunner-app directory with:
`TIMING=1 yarn  eslint --max-warnings 0 . `
On a M1 mac It outputs:
```
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
tailwindcss/no-contradicting-classname  |  9409.590 |    42.0%
tailwindcss/enforces-shorthand          |  4583.070 |    20.4%
tailwindcss/classnames-order            |  2386.195 |    10.6%
tailwindcss/no-custom-classname         |  2032.716 |     9.1%
@typescript-eslint/no-misused-promises  |   987.254 |     4.4%
import/namespace                        |   387.072 |     1.7%
@typescript-eslint/no-floating-promises |   286.450 |     1.3%
@typescript-eslint/no-unsafe-assignment |   274.832 |     1.2%
import/no-cycle                         |   185.191 |     0.8%
@typescript-eslint/no-unsafe-argument   |    93.103 |     0.4%
```

This issue appears to be tracked here but is old:
https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276

### PR DESCRIPTION
**Pull request by minhd-vu**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

- I added these settings to the DFS repo's `eslint.config.js` and it seems to be speeding it up.

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**Code formatting**

**Closing issues**

Put `Closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

- Closes #395

### CODE REVIEW

**Comment by psirenny** [comment]
I think I ported over the changes to the `dfs-app` project correctly but it still seems slow 😞.

**Comment by minhd-vu** [comment]
> I think I ported over the changes to the `dfs-app` project correctly but it still seems slow 😞.

Can you show me what steps you're doing so I can replicate it?

**Comment by psirenny** [comment]
I made the following change to [dfs/packages-app/eslint.config.js](https://github.com/spear-ai/dfs/blob/main/packages/dfs-app/eslint.config.js#L37):

```diff
import {
  baseEslintConfig,
  graphqlEslintConfig,
  javascriptFamilyFileList,
  nextEslintConfig,
  prettierConfig,
} from "@spear-ai/eslint-config";

const eslintConfig = [
  {
    ignores: [
      "**/.next/*",
      "**/__generated__/*",
      "**/coverage/*",
      "**/data/*",
      "**/dist/*",
      "**/public/*",
      "**/example-data/*",
      "**/exported-schema.mjs",
      "**/graphql/pothos/__generated__",
      "**/messages/__generated__",
      "**/schema.graphql",
      ".benchmark-output.json",
      "next-env.d.ts",
    ],
  },
  ...baseEslintConfig,
  ...nextEslintConfig,
  ...graphqlEslintConfig,
  prettierConfig,
  {
    files: javascriptFamilyFileList,
    rules: {
      // SWC doesn’t support the RegExp `v` flag yet
      // See: https://github.com/swc-project/swc/issues/8462
      "regexp/require-unicode-sets-regexp": ["off"],
    },
+   settings: {
+     /**
+      * Performance issue with the plugin.
+      * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/276
+      * @see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/174
+      */
+     tailwindcss: {
+       cssFiles: [],
+     },
+   },
  },
];
```

and also to the node modules just to be extra sure:
* node_modules/@spear-ai/eslint-config/dist/index.cjs
* node_modules/@spear-ai/eslint-config/dist/index.js
* ../../node_modules/@spear-ai/eslint-config/dist/index.cjs
* ../../node_modules/@spear-ai/eslint-config/dist/index.js

**Comment by minhd-vu** [comment]
@psirenny Ah okay, I tried recreating your issue. I looks like the first save you do will take the long amount of time, but I noticed that subsequent saves are much faster. I think there may be some caching done which speeds it up. Could you try testing again over a longer period to see if this helps?

**Comment by minhd-vu** [comment]
So I tried setting the rules to warnings:
```javascript
    rules: {
      // SWC doesn’t support the RegExp `v` flag yet
      // See: https://github.com/swc-project/swc/issues/8462
      "regexp/require-unicode-sets-regexp": ["off"],
      "tailwindcss/classnames-order": ["warn"],
      "tailwindcss/no-contradicting-classname": ["warn"],
      "tailwindcss/no-custom-classname": ["warn"],
    },
```
I noticed that it still runs pretty slowly on save, and subsequent runs run a lot faster once it's cached. It looks like the eslint on save only speeds up when turned off. I'm thinking of a couple of potential solutions for this:
1. Increase the cache expiration. I tried looking into this but I didn't find anything that was useful.
2. I think a potential solution is to disable some of the rules that are on-save and only have those run by the CI. It looks like you can configure the vscode plugin to ignore some of the eslint rules.
    - Issue: https://github.com/microsoft/vscode-eslint/issues/902
    - I think this should be the solution we go with to improve DX.

**Comment by psirenny** [comment]
> I think a potential solution is to disable some of the rules that are on-save and only have those run by the CI. It looks like you can configure the vscode plugin to ignore some of the eslint rules.
> * Issue: [Feature request: option to disable certain rules microsoft/vscode-eslint#902](https://github.com/microsoft/vscode-eslint/issues/902)
> * I think this should be the solution we go with to improve DX.

Ahh, this is perfect! It seems we'll have to do this per project workspace but that's ok. Do you want to try editing the `workspace.code-workspace` in DFS?

**Pull request closed without merging**
